server:
  port: 8090

logging:
  level:
    root: info
    ge.atm.bankservice: ${LOG_LEVEL:debug}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/atm-emulator}
    username: ${DB_USER:atm}
    password: ${DB_PASSWORD:thisistoosimple}
  flyway:
    enabled: true
  jpa:
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

bank-service:
  auth-token-header-name: X-API-KEY
  auth-token: ${BANK_SERIVCE_API_KEY:some-long-api-key}
