server:
  port: 8090

logging:
  level:
    root: ${LOG_LEVEL:info}

spring:
#  datasource:
  #    driverClassName: org.postgresql.Driver
  #    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
  #    username: ${DB_USER:postgres}
  #    password: ${DB_PASSWORD:password}
  #  flyway:
  #    enabled: false
  #  jpa:
  #    show-sql: false
  #    properties:
  #      hibernate:
  #        format_sql: true
  #    hibernate:
  #      ddl-auto: create
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/atm-emulator}
    username: ${DB_USER:atm}
    password: ${DB_PASSWORD:thisistoosimple}
  flyway:
    enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

bank-service:
  auth-token-header-name: X-API-KEY
  auth-token: ${BANK_SERIVCE_API_KEY:some-long-api-key}