server:
  port: 8080

jwt:
  token:
    secret: MySecretJWTMySecretJWTMySecretJWTMySecretJWTMySecretJWTMySecretJWTMySecretJWTMySecretJWTMySecretJWTMySecretJWTMySecretJWTMySecretJWT
    expirationInSeconds: 10000

bank-service:
  base-path: ${BANK_SERIVCE_URL:http://localhost:8090}
  auth-token-header-name: X-API-KEY
  auth-token: ${BANK_SERIVCE_API_KEY:some-long-api-key}